build image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USER} --password-stdin ${REGISTRY}
  script:
    - docker buildx build -t ${REGISTRY}/frontend/gf-frontend:$CI_COMMIT_SHORT_SHA -t ${REGISTRY}/frontend/gf-frontend:latest .
    - docker push ${REGISTRY}/frontend/gf-frontend:$CI_COMMIT_SHORT_SHA
    - docker push ${REGISTRY}/frontend/gf-frontend:latest
  only:
    - main
    - master
